/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container": "#efecf5",
        "on-primary-fixed": "#000767",
        "on-primary": "#ffffff",
        "surface-container-high": "#eae7ef",
        "secondary": "#b6171e",
        "primary": "#000666",
        "on-secondary-fixed-variant": "#930010",
        "on-surface-variant": "#454652",
        "surface-container-highest": "#e4e1ea",
        "tertiary-fixed": "#a3f69c",
        "inverse-primary": "#bdc2ff",
        "on-primary-container": "#8690ee",
        "surface": "#fbf8ff",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#410003",
        "on-secondary-container": "#fffbff",
        "tertiary-fixed-dim": "#88d982",
        "on-error": "#ffffff",
        "outline-variant": "#c6c5d4",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#ffb3ac",
        "on-background": "#1b1b21",
        "secondary-fixed": "#ffdad6",
        "primary-fixed": "#e0e0ff",
        "outline": "#767683",
        "surface-variant": "#e4e1ea",
        "on-tertiary-fixed-variant": "#005312",
        "surface-bright": "#fbf8ff",
        "on-tertiary-container": "#5aa958",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f5f2fb",
        "primary-container": "#1a237e",
        "on-tertiary-fixed": "#002204",
        "inverse-on-surface": "#f2eff8",
        "inverse-surface": "#303036",
        "secondary-container": "#da3433",
        "on-tertiary": "#ffffff",
        "surface-dim": "#dbd9e1",
        "tertiary": "#002103",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "tertiary-container": "#003909",
        "on-primary-fixed-variant": "#343d96",
        "on-surface": "#1b1b21",
        "primary-fixed-dim": "#bdc2ff",
        "background": "#fbf8ff",
        "surface-tint": "#4c56af"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        base: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        gutter: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "32px"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "title-lg": ["Inter", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "mono-data": ["Inter", "monospace"]
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "title-lg": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "title-md": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "mono-data": ["14px", { lineHeight: "20px", fontWeight: "500" }]
      }
    },
  },
  plugins: [],
}
